#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_"
else
    scp "$1" "$2" "$3" "$4"
fi
