#!/usr/bin/env bash
# Install nginx on my web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Holberton School
# Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo systemctl start nginx
