#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me is redirecting
# to another page
sudo apt-get -y update
sudo apt-get -y install nginx
NEW="location /redirect_me {\nrewrite ^/(.*)$ https://youtu.be/QH2-TGUlwu4 permanent;\n}\n"
FILE="/etc/nginx/sites-available/default"
sudo sed -i "35i $NEW" $FILE
sudo service nginx restart
