#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me is redirecting
# to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo systemctl start nginx
FILE="/etc/nginx/sites-available/default"
sudo sed -i '42i rewrite ^/redirect_me/$ https://youtu.be/QH2-TGUlwu4 permanent;\n' $FILE
sudo systemctl restart nginx
