#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains
# the string "Ceci n'est pas une page"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo systemctl start nginx
sudo chown -R ubuntu:ubuntu /var/www
sudo echo "Ceci n'est pas une page\n" > /var/www/html/404.html
sudo sed -i '42i error_page 404 /404.html;\n' /etc/nginx/sites-available/default
sudo systemctl restart nginx
