#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains
# the string "Ceci n'est pas une page"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo apt-get -y update"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo apt-get -y install nginx"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo systemctl start nginx"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo chown -R ubuntu:ubuntu /var/www"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo echo 'Ceci n'est pas une page' > /var/www/html/404.html"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo sed -i '42i error_page 404 /404.html;' /etc/nginx/sites-available/default"
ssh -i ~/.ssh/holberton ubuntu@34.74.170.251 "sudo systemctl restart nginx"
