#!/usr/bin/env bash
# This bash script installs and configures HAproxy on your lb-01 server
# so that is sends traffic to web-01 and web-02.
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*
FRONTEND="frontend 1065-lb-01\n\tbind *:80\n\tdefault_backend nginx_pool\n"
BACKEND="backend nginx_pool\n\tbalance roundrobin\n\tmode http\n\tserver 1065-web-01 104.196.5.171:80 check\n\tserver 1065-web-02 34.74.56.64:80 check\n"
sudo echo -e $FRONTEND >> /etc/haproxy/haproxy.cfg
sudo echo -e $BACKEND >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
