#!/usr/bin/env bash
# Bash script that configures a server to listening on port 80 of all
# the servers active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart