#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but in the 9th line
# it also prints "Hi"
i=1
while [ $i -le 10 ]; do
    if [ $i = 9 ]; then
	echo "Holberton School"
	echo "Hi"
    else
	echo "Holberton School"
    fi
    (( i++ ))
done
