#!/usr/bin/env bash
# This Bash script configures the container to fit the below requirements
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# I cannot use apt-get remove
pkill apache2
sudo chmod u+w /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo su nginx -c "sudo service nginx start"
