#!/usr/bin/env bash
# This Bash script configures the container to fit the below requirements
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# I cannot use apt-get remove
sudo chmod u+w /etc/nginx/nginx.conf
sudo sed -i '1 s/^.*$/user nginx;/'
